#!/usr/bin/env node
/**
 * Team Start Hook - Initialize team monitoring
 * cAgents V9.0 - Agent Teams Integration
 *
 * This hook runs when a team session starts to initialize
 * team-specific tracking and monitoring.
 *
 * 100% Self-Contained: Uses only built-in Node.js modules.
 *
 * Input (stdin): JSON with session context
 * Output (stdout): JSON with system message
 */

// CRITICAL: Wrap everything in try-catch for plugin resilience
try {

const fs = require('fs');
const path = require('path');

// Try to load hook-utils, fall back to inline implementations
let utils;
try {
  utils = require('./hook-utils.cjs');
} catch {
  // Minimal inline fallbacks for plugin mode
  utils = {
    AGENT_MEMORY_DIR: path.join(process.cwd(), 'Agent_Memory'),
    SESSION_PREFIXES: ['run_', 'optimize_', 'review_', 'designer_', 'team_'],
    readStdin: () => Promise.resolve({}),
    extractYamlValue: () => null,
    safeRead: () => null,
    ensureDir: (d) => { try { fs.mkdirSync(d, { recursive: true }); } catch {} return d; },
    getTimestampSlug: (d = new Date()) => d.toISOString().replace(/[:.]/g, '-').replace('T', '_').slice(0, 19)
  };
}

const { readStdin, AGENT_MEMORY_DIR, ensureDir, getTimestampSlug, safeRead, extractYamlValue } = utils;

/**
 * Check if Agent Teams is available
 */
function isAgentTeamsAvailable() {
  return process.env.CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS === '1';
}

/**
 * Find team session from context or recent sessions
 */
function findTeamSession(input) {
  // Check if session_id is provided
  if (input.session_id && input.session_id.startsWith('team_')) {
    const sessionDir = path.join(AGENT_MEMORY_DIR, 'sessions', input.session_id);
    if (fs.existsSync(sessionDir)) {
      return sessionDir;
    }
  }

  // Find most recent team session
  const sessionsDir = path.join(AGENT_MEMORY_DIR, 'sessions');
  if (!fs.existsSync(sessionsDir)) return null;

  const teamSessions = fs.readdirSync(sessionsDir)
    .filter(d => d.startsWith('team_'))
    .sort()
    .reverse();

  if (teamSessions.length === 0) return null;

  // Return most recent that's not completed
  for (const session of teamSessions) {
    const statusFile = path.join(sessionsDir, session, 'status.yaml');
    const content = safeRead(statusFile);
    if (!content) continue;

    const phase = extractYamlValue(content, 'phase');
    if (phase && phase !== 'completed' && phase !== 'failed') {
      return path.join(sessionsDir, session);
    }
  }

  return null;
}

/**
 * Initialize team monitoring structure
 */
function initializeTeamMonitoring(sessionDir) {
  const teamDir = path.join(sessionDir, 'team');
  const messagesDir = path.join(teamDir, 'messages');
  const metricsDir = path.join(teamDir, 'metrics');

  // Ensure directories exist
  ensureDir(teamDir);
  ensureDir(messagesDir);
  ensureDir(metricsDir);

  // Initialize timing metrics if not exists
  const timingFile = path.join(metricsDir, 'timing.yaml');
  if (!fs.existsSync(timingFile)) {
    const timingContent = `# Team Timing Metrics
# Auto-generated by team-start.cjs

session_id: ${path.basename(sessionDir)}
started_at: "${new Date().toISOString()}"
completed_at: null
total_duration_seconds: 0

phases:
  planning:
    started_at: null
    completed_at: null
    duration_seconds: 0
  team_execution:
    started_at: null
    completed_at: null
    duration_seconds: 0
  validation:
    started_at: null
    completed_at: null
    duration_seconds: 0

work_items: {}
`;
    fs.writeFileSync(timingFile, timingContent);
  }

  // Initialize parallelism metrics if not exists
  const parallelismFile = path.join(metricsDir, 'parallelism.yaml');
  if (!fs.existsSync(parallelismFile)) {
    const parallelismContent = `# Team Parallelism Metrics
# Auto-generated by team-start.cjs

session_id: ${path.basename(sessionDir)}

analysis:
  total_items: 0
  parallelizable_items: 0
  sequential_items: 0
  parallelism_score: 0.0
  critical_path_length: 0

utilization:
  peak_concurrent_members: 0
  average_concurrent_members: 0.0
  idle_time_seconds: 0
  efficiency_score: 0.0

speedup:
  estimated_sequential_time: 0
  actual_parallel_time: 0
  speedup_factor: 0.0
`;
    fs.writeFileSync(parallelismFile, parallelismContent);
  }

  return true;
}

/**
 * Main hook execution
 */
async function main() {
  const input = await readStdin();

  try {
    const sessionDir = findTeamSession(input);

    if (!sessionDir) {
      // No active team session, nothing to do
      console.log(JSON.stringify({ continue: true }));
      return;
    }

    const teamsAvailable = isAgentTeamsAvailable();
    const initialized = initializeTeamMonitoring(sessionDir);

    if (initialized) {
      console.error(`[TeamStart] Initialized team monitoring for ${path.basename(sessionDir)}`);
      console.error(`[TeamStart] Agent Teams available: ${teamsAvailable}`);

      const message = teamsAvailable
        ? `Team session initialized with full Agent Teams support.`
        : `Team session initialized in fallback mode (parallel Tasks).`;

      console.log(JSON.stringify({
        continue: true,
        systemMessage: message
      }));
    } else {
      console.log(JSON.stringify({ continue: true }));
    }

  } catch (error) {
    console.error(`[TeamStart] Error: ${error.message}`);
    console.log(JSON.stringify({ continue: true }));
  }
}

main();

} catch (e) {
  // Top-level catch for plugin resilience - always output valid JSON
  console.log(JSON.stringify({ continue: true }));
}
