/**
 * WI-B6 regression: agent_tree.yaml writer/reader schema contract.
 *
 * ROOT CAUSE THIS PINS (session act_subagent-token-budget_260909_001, ENG-OBS-5):
 * `agent_tree.yaml` had ONE shape in the writer's imagination and another in every
 * reader's. `.claude/skills/act/SKILL.md` ACTION 1 said only "self-register as root
 * agent", which invites a `root:` + `children:` tree. Every reader in
 * verify-completion.cjs counts spawns from a top-level `agents:` list keyed `- id:`.
 *
 * The mismatch was NOT merely cosmetic, and it broke BOTH directions at once:
 *   - WRITER: subagent-tracker.cjs bailed at its `!parsed.agents` guard
 *     ("missing agents: key — skipping append") and appended NOTHING for the rest
 *     of the session. That is why the tracker wrote 0 lines in the affected
 *     session while writing 1291 lines in designer_census-postcut_260805_001.
 *   - READERS: the same file read as "no child agents spawned", producing
 *     `DELEGATION VIOLATION` and BLOCKING Stop twice on a session that had really
 *     spawned five agents.
 *
 * Tests 1-3 are the contract required by ENG-OBS-5: a freshly-initialized tree
 * written per SKILL.md ACTION 1 must be parseable by the SAME code path
 * verify-completion.cjs uses, and a session with N spawns must report N.
 * Tests 4-7 pin the writer self-heal and the denied/failed-spawn records.
 *
 * Every assertion runs against the REAL hook files — no reimplementation.
 */

import { describe, it, expect, beforeAll, afterAll, beforeEach } from 'vitest';
import { existsSync, mkdirSync, rmSync, readFileSync, writeFileSync, mkdtempSync } from 'fs';
import { join } from 'path';
import { tmpdir } from 'os';
import { spawnSync } from 'child_process';

const REPO_ROOT = process.cwd();
const TRACKER = join(REPO_ROOT, '.claude', 'hooks', 'subagent-tracker.cjs');
const VERIFY = join(REPO_ROOT, '.claude', 'hooks', 'verify-completion.cjs');
const SKILL_MD = join(REPO_ROOT, '.claude', 'skills', 'act', 'SKILL.md');

let TMP_PROJECT;
let SESSIONS_DIR;

const NOW = Date.now();
const iso = (msAgo) => new Date(NOW - msAgo).toISOString();

/**
 * THE CANONICAL FRESH TREE — exactly what .claude/skills/act/SKILL.md ACTION 1
 * now instructs /act to write at session init: a top-level `agents:` LIST whose
 * first entry is the depth-0 pipeline root. This is the fixture Test 1 feeds
 * through the real reader.
 */
function freshCanonicalTree(sid) {
  return [
    '# Agent Tree - cAgents Audit Trail',
    `# Session: ${sid}`,
    '# Generated by /act self-registration',
    'agents:',
    '  - id: "pipeline"',
    '    type: "cagents:act"',
    '    parent: "root"',
    '    depth: 0',
    `    spawned_at: "${iso(60 * 1000)}"`,
    '    stopped_at: null',
    '    cagents_type: "cagents:act"',
    '    short_role: "Pipeline Engine"',
    `    session: "${sid}"`,
    '',
  ].join('\n');
}

/** The BROKEN shape ENG-OBS-5 caught in the wild. No `agents:` key at all. */
function brokenRootChildrenTree(sid) {
  return [
    'root:',
    '  agent: cagents:act',
    `  session: ${sid}`,
    `  spawned_at: "${iso(60 * 1000)}"`,
    '  stopped_at: null',
    'children: []',
    '',
  ].join('\n');
}

function makeSession(slug, pipelineState, treeContent) {
  const sid = `act_b6-${slug}-${Math.random().toString(36).slice(2, 8)}_260909_001`;
  const dir = join(SESSIONS_DIR, sid);
  mkdirSync(join(dir, 'workflow'), { recursive: true });
  writeFileSync(
    join(dir, 'status.yaml'),
    [
      `session_id: ${sid}`,
      `pipeline_state: ${pipelineState}`,
      `last_updated_at: "${iso(2 * 60 * 1000)}"`,
      'state_history:',
      `  - state: ${pipelineState}`,
      `    entered_at: "${iso(2 * 60 * 1000)}"`,
      '',
    ].join('\n')
  );
  if (treeContent !== null) {
    writeFileSync(join(dir, 'workflow', 'agent_tree.yaml'), treeContent);
  }
  return { sid, dir };
}

const hookEnv = () => ({
  ...process.env,
  CLAUDE_PROJECT_DIR: TMP_PROJECT,
  CAGENTS_ACTIVE_SESSION: '',
  CAGENTS_SESSION_ID: '',
});

/** Run the REAL Stop hook (the code path that reads agent_tree.yaml). */
function runVerify(sid) {
  const r = spawnSync('node', [VERIFY], {
    input: JSON.stringify({ session_id: sid, stop_hook_active: false, hook_event_name: 'Stop' }),
    encoding: 'utf8',
    timeout: 60000,
    env: hookEnv(),
  });
  if (r.error) throw new Error(`verify-completion spawn failed: ${r.error.message}`);
  if (r.status === null) throw new Error(`verify-completion timed out. stderr=${r.stderr}`);
  let parsed;
  try {
    parsed = JSON.parse(r.stdout);
  } catch {
    throw new Error(`verify-completion stdout not JSON: "${r.stdout}"\nstderr: ${r.stderr}`);
  }
  return { ...parsed, stderr: r.stderr };
}

/** Run the REAL SubagentStart tracker (the writer). */
function runTracker(sid, sessionDirName, agentType, agentId) {
  const r = spawnSync('node', [TRACKER], {
    input: JSON.stringify({
      agent_type: agentType,
      agent_id: agentId,
      session_id: sid,
      tool_input: { subagent_type: agentType, prompt: `SESSION DIR: ${sessionDirName}\nDo work.` },
    }),
    encoding: 'utf8',
    timeout: 30000,
    env: { ...hookEnv(), CAGENTS_ACTIVE_SESSION: sid },
  });
  if (r.error) throw new Error(`subagent-tracker spawn failed: ${r.error.message}`);
  if (r.status === null) throw new Error(`subagent-tracker timed out. stderr=${r.stderr}`);
  return { stdout: r.stdout, stderr: r.stderr, status: r.status };
}

describe('WI-B6 agent_tree.yaml schema contract (writer <-> readers)', () => {
  beforeAll(() => {
    TMP_PROJECT = mkdtempSync(join(tmpdir(), 'cagents-b6-'));
    SESSIONS_DIR = join(TMP_PROJECT, 'cagents-memory', 'sessions');
    mkdirSync(SESSIONS_DIR, { recursive: true });
  });

  afterAll(() => {
    try {
      if (TMP_PROJECT && existsSync(TMP_PROJECT)) rmSync(TMP_PROJECT, { recursive: true, force: true });
    } catch {}
  });

  // ------------------------------------------------------------------ (a)
  it('Test 1 — a freshly-initialized tree written per SKILL.md ACTION 1 is parseable by the SAME reader verify-completion.cjs uses, and is NOT called a delegation violation', () => {
    const { sid, dir } = makeSession('fresh', 'PLANNED', null);
    writeFileSync(join(dir, 'workflow', 'agent_tree.yaml'), freshCanonicalTree(sid));

    const out = runVerify(sid);
    const blob = JSON.stringify(out);

    // The canonical fresh tree must never be reported as a schema defect.
    expect(blob, 'canonical fresh tree must not be flagged as a schema defect').not.toContain(
      'AGENT TREE SCHEMA DEFECT'
    );
    // And it must never hard-block Stop.
    expect(out.decision, 'a well-formed fresh tree must not block Stop').not.toBe('block');
  });

  it('Test 1b — the SKILL.md ACTION 1 instruction actually mandates the `agents:` list (and forbids root/children)', () => {
    const skill = readFileSync(SKILL_MD, 'utf8');
    const action1 = skill.split('**ACTION 1**')[1].split('**ACTION 1b**')[0];
    expect(action1, 'ACTION 1 must name the mandatory `agents:` key').toMatch(/agents:/);
    expect(action1, 'ACTION 1 must explicitly forbid the root/children shape').toMatch(
      /root:\s*\/\s*`?children|`root:`\/`children:`|root:`\/`children/
    );
  });

  // ------------------------------------------------------------------ (b)
  it('Test 2 — a session with N spawns reports N (writer and reader agree on the count)', () => {
    const N = 4;
    const { sid } = makeSession('countn', 'PLANNED', null);
    const dir = join(SESSIONS_DIR, sid);
    writeFileSync(join(dir, 'workflow', 'agent_tree.yaml'), freshCanonicalTree(sid));

    for (let i = 0; i < N; i++) {
      const res = runTracker(sid, sid, 'cagents:backend-developer', `ab6count${i}`);
      expect(res.status, `tracker spawn ${i} must exit 0. stderr=${res.stderr}`).toBe(0);
    }

    const tree = readFileSync(join(dir, 'workflow', 'agent_tree.yaml'), 'utf8');

    // Reader arm 1: the `- id:` list counter used by verify-completion.cjs
    // (outcomeAgentCount + the childAgentCount fallback). N spawns + the depth-0
    // pipeline root entry.
    const idEntries = tree.match(/^\s*- id:/gm) || [];
    expect(idEntries.length, `expected ${N} spawns + 1 root entry`).toBe(N + 1);

    // Reader arm 2: the depth>=1 counter (the PRIMARY delegation-violation count).
    const depthEntries = tree.match(/\bdepth:\s*([1-9]\d*)\b/g) || [];
    expect(depthEntries.length, `expected exactly ${N} depth>=1 child agents`).toBe(N);
  });

  it('Test 3 (FAIL-before, PASS-after) — a root/children tree is reported as a SCHEMA DEFECT with delegation UNKNOWN, never as a false DELEGATION VIOLATION, and never blocks', () => {
    const { sid } = makeSession('broken', 'PLANNED', null);
    const dir = join(SESSIONS_DIR, sid);
    writeFileSync(join(dir, 'workflow', 'agent_tree.yaml'), brokenRootChildrenTree(sid));

    const out = runVerify(sid);
    const blob = JSON.stringify(out) + out.stderr;

    // Pre-fix this said "no child agents spawned ... work was self-handled" — a
    // fabricated claim about the user's work. It must now name the real defect.
    expect(blob, 'must name the schema defect').toContain('AGENT TREE SCHEMA DEFECT');
    expect(blob, 'must not assert self-handling from an unreadable instrument').not.toContain(
      'work was self-handled or the session was abandoned'
    );
    // Fail OPEN: a defect in OUR instrument must never deadlock the user's Stop.
    expect(out.decision, 'a schema defect must never hard-block Stop').not.toBe('block');
  });

  // ------------------------------------------------------------------ writer self-heal
  it('Test 4 (FAIL-before, PASS-after) — the tracker SELF-HEALS a root/children tree instead of silently dropping every spawn', () => {
    const { sid } = makeSession('selfheal', 'PLANNED', null);
    const dir = join(SESSIONS_DIR, sid);
    const treeFile = join(dir, 'workflow', 'agent_tree.yaml');
    writeFileSync(treeFile, brokenRootChildrenTree(sid));
    const before = readFileSync(treeFile, 'utf8');

    const res = runTracker(sid, sid, 'cagents:planner', 'ab6heal1');
    const after = readFileSync(treeFile, 'utf8');

    // Pre-fix: byte-identical (the "missing agents: key — skipping append" bail).
    expect(after, 'the tracker must no longer leave the tree untouched').not.toBe(before);
    expect(after, 'the missing `agents:` key must be added').toMatch(/^agents:/m);
    expect(after, 'the spawn must actually be recorded').toContain('ab6heal1');
    // Non-destructive: `root:` is preserved, never rewritten away.
    expect(after, '`root:` must be preserved as-is').toMatch(/^root:/m);
    // LOUD, never silent — on stderr AND to the model.
    expect(res.stderr, 'the repair must be announced on stderr').toMatch(/not in the canonical|NOT in the canonical/i);
    expect(res.stdout, 'the repair must be surfaced to the model').toContain('migrated in place');
  });

  // ------------------------------------------------------------------ (Part 2)
  it('Test 5 (new capability) — a DENIED spawn writes a record with its reason', () => {
    const { sid } = makeSession('denied', 'PLANNED', null);
    const dir = join(SESSIONS_DIR, sid);
    writeFileSync(join(dir, 'workflow', 'agent_tree.yaml'), freshCanonicalTree(sid));

    const r = spawnSync(
      'node',
      [
        TRACKER,
        '--record-failure',
        JSON.stringify({
          attempt_id: 'ab6denied1',
          attempted_type: 'cagents:backend-developer',
          status: 'denied',
          reason: 'session-init-gate: no active session',
          session_dir: dir,
          attempted_depth: 2,
        }),
      ],
      { encoding: 'utf8', timeout: 30000, env: hookEnv() }
    );
    expect(r.status, `record-failure must exit 0. stderr=${r.stderr}`).toBe(0);

    const tree = readFileSync(join(dir, 'workflow', 'agent_tree.yaml'), 'utf8');
    expect(tree, 'a denied spawn must leave a record').toContain('spawn_failures:');
    expect(tree).toContain('ab6denied1');
    expect(tree, 'the record must carry its REASON').toContain('session-init-gate: no active session');
    expect(tree).toMatch(/status:\s*denied/);

    // The global audit log carries it too (survives session loss).
    const log = readFileSync(
      join(TMP_PROJECT, 'cagents-memory', '_system', 'logs', 'agent_spawns.log'),
      'utf8'
    );
    expect(log, 'the denial must reach the global audit log').toMatch(/SPAWN_DENIED.*ab6denied1/);
  });

  it('Test 6 (INVARIANT — a denial must never be able to fake delegation) — spawn_failures records are invisible to every reader counter', () => {
    const { sid } = makeSession('nofake', 'PLANNED', null);
    const dir = join(SESSIONS_DIR, sid);
    const treeFile = join(dir, 'workflow', 'agent_tree.yaml');
    // A tree with the depth-0 root ONLY — zero real child spawns.
    writeFileSync(treeFile, freshCanonicalTree(sid));

    for (let i = 0; i < 3; i++) {
      spawnSync(
        'node',
        [
          TRACKER,
          '--record-failure',
          JSON.stringify({
            attempt_id: `ab6fake${i}`,
            attempted_type: 'cagents:backend-developer',
            status: 'denied',
            reason: 'gate denied',
            session_dir: dir,
            attempted_depth: 2,
          }),
        ],
        { encoding: 'utf8', timeout: 30000, env: hookEnv() }
      );
    }

    const tree = readFileSync(treeFile, 'utf8');
    expect(tree, 'the denials must be on disk for the assertions below to mean anything').toContain('ab6fake2');

    // Scope to the failures region and assert each reader regex sees NOTHING.
    const failRegion = tree.split(/^spawn_failures:/m)[1] || '';
    expect(failRegion.length, 'spawn_failures region must exist').toBeGreaterThan(0);
    expect(failRegion.match(/^\s*- id:/gm), '`- id:` child counter must not see a denial').toBeNull();
    expect(failRegion.match(/\bdepth:\s*([1-9]\d*)\b/g), 'depth counter must not see a denial').toBeNull();
    expect(failRegion.match(/stopped_at:\s*null/), 'a denial must never look like a live running child').toBeNull();
    expect(
      failRegion.match(new RegExp(`^\\s*(?:-\\s*)?(?:agent_type|cagents_type|type):\\s*["']?cagents:backend-developer`, 'im')),
      'a denial must not satisfy the next-stage-agent probe'
    ).toBeNull();

    // Whole-tree: still exactly zero depth>=1 children despite 3 denials.
    expect((tree.match(/\bdepth:\s*([1-9]\d*)\b/g) || []).length, '3 denials must add 0 spawned children').toBe(0);
  });

  it('Test 7 (INVARIANT — advisory only) — the tracker never denies, never blocks, and exits 0 on every path', () => {
    const { sid } = makeSession('advisory', 'PLANNED', null);
    const dir = join(SESSIONS_DIR, sid);

    // (i) unusable tree, (ii) canonical tree, (iii) no tree at all
    const cases = [
      ['malformed', ': : not [ valid ] yaml : ::\n\t\tbad'],
      ['canonical', freshCanonicalTree(sid)],
    ];
    for (const [label, content] of cases) {
      writeFileSync(join(dir, 'workflow', 'agent_tree.yaml'), content);
      const res = runTracker(sid, sid, 'cagents:qa-lead', `ab6adv-${label}`);
      expect(res.status, `${label}: tracker must exit 0`).toBe(0);
      const out = JSON.parse(res.stdout.trim());
      expect(out.hookSpecificOutput?.permissionDecision, `${label}: must never deny`).toBeUndefined();
      expect(out.decision, `${label}: must never block`).toBeUndefined();
      expect(JSON.stringify(out), `${label}: must never emit a deny verdict`).not.toContain('"deny"');
    }
  });
});
